# fly.toml app configuration file generated for dan-edwards-creative on 2024-11-02T00:22:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dan-edwards-creative'
primary_region = 'lhr'

[build]
  no_retry = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'on-failure'
  retries = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
