# fly.toml app configuration file generated for dan-digresses on 2024-10-27T22:46:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dan-digresses'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'on-failure'
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
